const products = [
    { id: 1, name: "Laptop", price: 80000, category: "Electronics" },
    { id: 2, name: "Mobile Phone", price: 30000, category: "Electronics" },
    { id: 3, name: "Headphones", price: 2500, category: "Electronics" },
    { id: 4, name: "Keyboard", price: 1500, category: "Accessories" },
    { id: 5, name: "Mouse", price: 800, category: "Accessories" },
    { id: 6, name: "Monitor", price: 20000, category: "Electronics" },
    { id: 7, name: "Webcam", price: 3500, category: "Electronics" },
    { id: 8, name: "Printer", price: 15000, category: "Electronics" },
    { id: 9, name: "USB Flash Drive", price: 1200, category: "Storage" },
    { id: 10, name: "External Hard Drive", price: 8500, category: "Storage" },
    { id: 11, name: "SSD 512GB", price: 7500, category: "Storage" },
    { id: 12, name: "Power Bank", price: 2500, category: "Accessories" },
    { id: 13, name: "Smart Watch", price: 6000, category: "Wearables" },
    { id: 14, name: "Bluetooth Speaker", price: 4500, category: "Audio" },
    { id: 15, name: "Gaming Mouse", price: 2200, category: "Gaming" },
    { id: 16, name: "Gaming Keyboard", price: 4500, category: "Gaming" },
    { id: 17, name: "Gaming Headset", price: 5500, category: "Gaming" },
    { id: 18, name: "Laptop Stand", price: 1800, category: "Accessories" },
    { id: 19, name: "Phone Charger", price: 1200, category: "Accessories" },
    { id: 20, name: "Wireless Charger", price: 2000, category: "Accessories" },
    { id: 21, name: "Tablet", price: 35000, category: "Electronics" },
    { id: 22, name: "Smartphone", price: 45000, category: "Electronics" },
    { id: 23, name: "Microphone", price: 4000, category: "Audio" },
    { id: 24, name: "Router", price: 3500, category: "Networking" },
    { id: 25, name: "WiFi Adapter", price: 1800, category: "Networking" },
    { id: 26, name: "Mechanical Keyboard", price: 6500, category: "Gaming" },
    { id: 27, name: "Graphics Tablet", price: 9000, category: "Accessories" },
    { id: 28, name: "LED Monitor Light", price: 2500, category: "Accessories" },
    { id: 29, name: "HDMI Cable", price: 700, category: "Accessories" },
    { id: 30, name: "Laptop Cooling Pad", price: 2200, category: "Accessories" }
];

export default products;